import { Store, WatchCallback, WatchMsg, Watcher } from "./global"

/**
 * Types of events generated by a WATCH of a STORE
 */
 export enum EVENTS_TYPES {
	ACTION = "action",
	MUTATION = "mutation",
}

/**
 * Groups of CALLBACK per "property name"
 */
 type WatchCallbackGroupByProp = { [nameProp: string]: Set<WatchCallback> }

/**
 * Groups of CALLBACK per STORE.
 * A WeakMap keyed by the store instance: when a store is no longer referenced
 * anywhere else (e.g. an ephemeral per-component store) it can be garbage
 * collected together with its watchers, even if `removeWatch` was never called.
 */
const listeners: WeakMap<Store, WatchCallbackGroupByProp> = new WeakMap()

/**
 * Deliver the event to all registered LISTENERS
 * @param key name of actionmutation
 * @param payload of action/mutator
 */
export function pluginEmit(type: EVENTS_TYPES, store: Store, key: string, payload: any, result: any) {

	const msg = { type, store, key, payload, result } as WatchMsg

	// if the store is not found do nothing
	if (!listeners.has(store)) return

	const storeActions = listeners.get(store)
	if (!storeActions) return

	const callbacksStoreJolly = storeActions["*"]
	if (callbacksStoreJolly) {
		for (const callback of callbacksStoreJolly) callback(msg)
	}

	// get all callbacks for the store and execute them
	const callbacks = storeActions[key]
	if (!callbacks) return
	for (const callback of callbacks) callback(msg)
}


/**
 * Inserts a WATCHER into JON
 */
export function addWatch({ store, actionName, callback }: Watcher) {

	// get or create storeActions
	let storeActions = listeners.get(store)
	if (!storeActions) {
		storeActions = {}
		listeners.set(store, storeActions)
	}

	// get or create action
	let callbacks = storeActions[actionName]
	if (!callbacks) {
		callbacks = new Set()
		storeActions[actionName] = callbacks
	}

	callbacks.add(callback)
}

/**
 * Removes a listener from JON
 * if `actionName` is `null` delete all listener of STORE
 * if `callback` is `null` delete all listener of `actionName`
 */
export function removeWatch({ store, actionName, callback }: Pick<Watcher, "store"> & Partial<Watcher>): void {

	// if exist get storeActions
	const storeActions = listeners.get(store)
	if (!storeActions) return

	// no actionName → remove ALL listeners of the store
	if (!actionName) {
		listeners.delete(store)
		return
	}

	// delete callback from storeActions
	const callbacks = storeActions[actionName]
	if (callbacks && callback) callbacks.delete(callback)

	// if there are no more callbacks for the action, delete it
	if (!callbacks || callbacks.size === 0 || !callback) {
		delete storeActions[actionName]
	}
	// if there are no more actions for the store, delete the store
	if (Object.keys(storeActions).length === 0) {
		listeners.delete(store)
	}
}